steps:

  #
  # Android builder base - used by React Native and React Native CLI
  #
  - label: ':docker: Build Android Builder base image'
    key: 'android-builder-base'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: android-builder-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base
      - docker-compose#v3.3.0:
          push: android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base

  - label: ':docker: Build RN Android Builder image'
    key: "android-builder-image"
    depends_on: 'android-builder-base'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.3.0:
          build: react-native-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.3.0:
          push: react-native-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}

  #
  # Test fixtures
  #
  - label: ':android: Build RN 0.60 apk'
    key: "rn-0-60-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.60"
      NOTIFIER_VERSION: 7.14.2
      LANG: "en_US.UTF-8"
    plugins:
      - docker-compose#v3.3.0:
          run: react-native-android-builder
    artifact_paths:
      - build/rn0.60.apk

  - label: ':android: Build RN 0.63 apk'
    key: "rn-0-63-apk"
    depends_on:
      - "android-builder-image"
    timeout_in_minutes: 60
    env:
      REACT_NATIVE_VERSION: "rn0.63"
      NOTIFIER_VERSION: 7.14.2
      LANG: "en_US.UTF-8"
    plugins:
      - docker-compose#v3.3.0:
          run: react-native-android-builder
    artifact_paths:
      - build/rn0.63.apk
