steps:

  #
  # CLI tests Maze Runner image
  #
  - label: ':docker: Build CLI test image'
    key: 'cli-maze-image'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.9.0:
          build: react-native-cli-tool-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  react-native-cli-tool-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:cli-maze-${BRANCH_NAME}
      - docker-compose#v3.9.0:
          push: react-native-cli-tool-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:cli-maze-${BRANCH_NAME}

  #
  # CLI tests
  #
  - label: ':runner: RN 0.60 CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_60"

  - label: ':runner: RN 0.61 CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_61"

  - label: ':runner: RN 0.62 CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_62"

  - label: ':runner: RN 0.63 CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_63"

  - label: ':runner: RN 0.63 Expo (ejected) CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_63_expo_ejected"

  - label: ':runner: RN 0.64 CLI tests'
    depends_on: "cli-maze-image"
    timeout_in_minutes: 20
    plugins:
      artifacts#v1.5.0:
        upload: ./test/react-native-cli/maze_output/**/*
      docker-compose#v3.9.0:
        pull: react-native-cli-tool-maze-runner
        run: react-native-cli-tool-maze-runner
        use-aliases: true
        command:
          - --fail-fast
          - --retry=2
          - features/cli-tests
    env:
      REACT_NATIVE_VERSION: "rn0_64"


  #
  # Built app test fixtures - iOS
  #
  - label: ':ios: Init and build RN 0.60 ipa 1'
    timeout_in_minutes: 30
    agents:
      queue: 'opensource-mac-cocoa-11'
    env:
      NOTIFIER_VERSION: 7.15.1
      DEBUG: true
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode11.app"
    artifact_paths: build/rn0_60.ipa
    commands:
      - test/react-native-cli/scripts/init-and-build-test.sh rn0_60

  - label: ':ios: Init and build RN 0.60 ipa 2'
    timeout_in_minutes: 30
    agents:
      queue: 'opensource-mac-cocoa-11'
    env:
      NOTIFIER_VERSION: 7.15.1
      DEBUG: true
      LANG: "en_US.UTF-8"
      DEVELOPER_DIR: "/Applications/Xcode11.app"
    artifact_paths: build/rn0_60.ipa
    commands:
      - test/react-native-cli/scripts/init-and-build-test.sh rn0_60
